---
title: 协程入门
tag: Kotlin
category: 协程
---

* 协程是一种非抢占式或者说是协作式的计算机程序并发调度的实现方案，程序可以主动挂起或者恢复执行。
* 线程当中的代码逻辑在线程抢占到 CPU 的时间片的时候才可以执行，否则就歇着
* 协程更轻量的意思是，协程并不会映射成内核线程或者其他资源，他的调用在用户态就可以搞定，任务之间是协作式，并非抢占式。
* 协程的三要素：上下文、启动模式、协程体
* 多个协程可以共用一个线程

* 协程的本质
  * 协程的挂起函数本质上就是一个回调，回调类型就是`Continuation`
  * 协程体的执行就是一个*状态机*，每一次遇到挂起函数，都是一次状态转移

<!-- more -->

## 通过 Retrofit 请求

通过 `Retrofit` 发送一个网络请求

```kotlin
interface GitHubServiceApi {
    @GET("users/{login}")
	fun getUser(@Path("login") login:String):Call<User>
}

data class User(val id:String, val name:String, val url:String)
```

`Retrofit` 初始化如下

```kotlin
val githubServiceApi by lazy {
    val retorfit = retrofit2.Retrofit.Builder()
        .baseUrl("https//api.github.com")
        .addConverterFacetory(GsonConverterFactory.create())
        .build()
    retrofit.create(GitHUbServiceApi::class.java)
}
```

发起网络请求

```kotlin
githubServiceApi.getUser("small")
.enqueue(object: Callback<User> {
    override fun onFailure(call: Call<User>, t: Throwable) {
        handler.post{showError(t)}
    }
    
    override fun onSuccess(call: Call<User>, response: Response<User>) {
        handler.post{
            response.body()?.let(::showUser) ?: showError(NullPointerException())
        }
    }
})
```



## 改造为携程

对于 `Retrofit` 改造为协程的方式有两种，分别通过 `CallAdapter` 和 `suspend` 函数

### CallAdapter 

该方法的本质是让接口的方法返回一个协程的 `Job`

```kotlin
interface GitHubServiceApi {
    @GET("users/{login}")
    fun getUser(@Path("login")login:String):Deferred<User>
}
```

> Deferred 是 Job 的子接口

同时需要为 `Retrofit` 添加对 `Deferred` 的支持

```groovy
implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'
```

对构造 `Retorfit` 的实例添加

```kotlin
val githubServiceApi by lazy {
    val retorfit = retrofit2.Retrofit.Builder()
        .baseUrl("https//api.github.com")
        .addConverterFactory(GsonConverterFactory.create())
        .addCallAdapterFactory(CoroutineCallAdapterFactroy())
        .build()
    retrofit.create(GitHubServiceApi::class.java)
}
```

通过上面的修改，那么我们的请求就可以这样写

```kotlin
GlobalScope.launch(Dispatchers.Main) {
    try{
        showUser(githubServiceApi.getUser("small").await())
    } catch (e: Exception) {
        shwoError(e)
    }
}
```

**Note:**  我们首先通过 `launch` 启动了一个协程，这类似于我们启动一个线程，`launch` 的参数有三个: 协程上下文、协程启动模式、协程体

```kotlin
public fun CorountineScope.launch(
	context:CorountineContext = EmptyCouroutineContext,// 上下文
    start: CoroutineStart = CoroutineStart.DEFGAULT, // 启动模式
    block: suspend CorountineScope.() -> UNit // 协程体
) :Job
```

**启动模式** 不是一个复杂的概念，默认直接俄允许调度执行

**上下文**可以有很多作用，包括*携带参数*、*拦截协程执行*等等，多数情况下我们不需要自己去实现上下文，只需要使用系统提供的就好。上下文有一个重要的作用就是切换线程，`Dispatchers.Main` 就是一个官方提供的上下文，它可以确保`launch` 启动的协程体运行在 UI 线程当中（除非你自己再 `launch` 的新和成提内部进行线程切换，或者启动运行再其他有线程切换能力的上下文的协程）

换句话说，在例子当中的整个 `launch` 内部，你看到的代码都是运行在UI线程中的，尽管 `getUser` 在执行的时候确实切换了线程，但返回结果的时候会再次切回来。直觉告诉我们 `getUser` 返回了要给 `Deferred` 类型，他的 `await` 方法会返回一个 `User` 对象，意味着 `await` 需要等待请求结果返回才可以继续执行，那么`await` 不会阻塞 UI 线程嘛？

当然不会。不然 `Deferred` 于 `Future`  又有上面区别的，这里`await`  很可疑。因为实际上是要给 `suspend` 函数。整个函数只能在协程体或者其他 `suspend` 函数内部被调用，就像是回调的语法糖一样，通过一个叫 `Continuation` 的接口来实现返回结果``

```kotlin
@SinceKotlin("1.3")
public interface Continuation<in T> {
    public val context:CoroutineContext
    public fun resumeWith(result:Result<T>)
}

@SinceKotlin("1.1")
public interface Continuation<in T> {
    public val context:CorouineContext
    public fun resume(value: T)
    public fun resumeWithException(exception: Throwable)
}

```

其实就是要给回调，有结果正常返回， `Continuation` 调用 `resume` 返回结果，否则调用 `resumeWithException` 来抛出异常。

因此，请求的代码执行流程本质上是一个异步回调

而之所以可以看起来是同步的，那就是编译器的黑魔法了

在虚拟机上 `await` 函数的真实样子是这样的

```
kotlin/coroutines/Deferred.await (Lkotlin/coroutines/Cotinuation;) LJava/lang/Object
```

即接收一个 `Continuation` 实例，返回 `Object` 这么一个函数，所以前面的代码可以理解为

```kotlin
// 不是正确代码，仅用来理解协程使用
GlobalScope.launch(Dispathcers.Main) {
    githubServiceApi.getUser("small").await(object: Continuation<User>{
        override fun resume(value: User) {
            showUser(value)
        }
        
        override fun resumeWithException(exception: Throwable) {
            showError(exception)
        }
    })
}
```

在 `await` 当中大致就是：

```kotlin
// 不是正确代码，仅用来理解协程使用
fun awiat(continuation:Continuation<user>):Any{
    ...// 切到非 UI 线程中执行，等待结果返回
    try {
        val user = ....// 这里执行任务
        handler.post {
            continuation.resume(user)
        }
    } catch(e: Exception) {
        handler.post{continuation.resumeWithException(e)}
    }
}
```

> 从运行机制上来讲，协程和回调没有本质的区别

### suspend  方式

`suspend` 函数是 Kotlin 编译器对协程支持的黑魔法，还是先看如何在Retrofit 中如何使用

> Retrofit 在 release 2.5.0 之后才会支持 suspend 函数

首先修改一下接口方法

```kotlin
@GET("users/{login}")
suspend fun getUser(@Path("login")login:String): User
```

这种情况下， `Retrofit` 会根据接口方法的生命来构造`Continuation` ，并且在内部封装了一个 `Call` 的异步请求(使用 `enqueue`) ，进而得到 User 实例。

```kotlin
GlobalScope.launch {
    try {
        showUser(githubServiceApi.getUser("small"))
    } catch (e: Exception) {
        showError(e)
    }
}
```

## 协程到底是什么

以前我们使用 Java 进行开发的时候，经常会遇到 *回调地域* ，使得代码的可读性急剧降低；也通过大量复杂的异步调用处理逻辑、异常；因为回调的存在，还得经常处理线程切换。随着代码体量的增加，各种问题频频爆发。

而 **协程** 可以帮我们优雅的处理掉这些

协程本身是一个脱离语言实现的概念。简单来说就是：

协程是一种非抢占式或者说协作式的计算机程序并发调度的实现，程序可以主动挂起或者恢复执行。经常听到的所谓的协程更轻量的意思是，协程并不会映射成内核线程或者其他重的资源，它的调度在用户态就可以搞定，任务之间的调度并非抢占式，而是协作式。

### Job

```kotlin
public interface Job: CoroutineContext.Element {
    ...
    public val isActive: Boolean
    public val isCompleted: Boolean
    public val isCancelled: Boolean
    
    public fun start():Boolean
    public fun cancel(cause: CancellationException? = null)
    public suspend fun join()
    ...
}
```

我们看一下 **Thread** 的定义

```java
public class Thread implements Runnable {
    ...
    public final native boolean isAlive();
    public synchronized void start(){}
    
    @Deprecated
    public final void stop(){}
    public final void join() throws InterruptedException{}
}
```

Thread 和 Job 的基本功能是一致的，他们都承载着一段代码逻辑，也都包含了这段代码的运行状态。